custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

service: audfprint

provider:
  name: aws
  runtime: python3.6
  timeout: 60

package:
  # individually: true
  exclude:
    - __pycache__/**
    - node_modules/**
    - tests/**
    - .git/**
    - '*.txt'
    - README.md
    - package.json
    - yarn.lock
    - Makefile
    - audfprint.py
    # - audio_read.py
    - dpwe_builder.py
    - dpwe_matcher.py
    - comp_file_lines.py

functions:
  create:
    handler: handler.create
  match:
    handler: handler.match

plugins:
  - serverless-python-requirements
